apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencv-fastapi-car-recognition
  labels:
    app: opencv-fastapi-car-recognition
spec:
  selector:
    matchLabels:
      app: opencv-fastapi-car-recognition
  replicas: 1
  template:
    metadata:
      labels:
        app: opencv-fastapi-car-recognition
    spec:
      containers:
        - name: opencv-fastapi-car-recognition
          image: a891/opencv-fastapi-car-recognition
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: opencv-fastapi-car-recognition
  name: opencv-fastapi-car-recognition
spec:
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32091
  selector:
    app: opencv-fastapi-car-recognition
  type: NodePort
